### ISSUE TITLE
Doesn't even start

### ISSUE THREAD

**Issue by profpandaa** [TeamOceanox/Ocean-Anticheat#2]
https://hastebin.com/usehiwuwel.cs

**Comment by TeamOceanox** [comment]
Ok hi this is a normal error. Its a error with the Timer check the anticheat is fine it starts and works that error will be fixed in 1.5

**Comment by profpandaa** [comment]
btw. improve your Speedcheck, the old AAC2BHop of LiquidBounce bypasses.

**Comment by TeamOceanox** [comment]
the speed and fly checks are in beta

**Comment by TeamOceanox** [comment]
the Error is Fixed in 1.6
